-- MySQL Script generated by MySQL Workbench
-- Thu Oct  8 17:31:29 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema home_organizer
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `home_organizer` ;

-- -----------------------------------------------------
-- Schema home_organizer
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `home_organizer` DEFAULT CHARACTER SET utf8 COLLATE utf8_polish_ci ;
USE `home_organizer` ;

-- -----------------------------------------------------
-- Table `home_organizer`.`group`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `home_organizer`.`group` ;

CREATE TABLE IF NOT EXISTS `home_organizer`.`group` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` TIMESTAMP NULL,
  `delete_time` TIMESTAMP NULL,
  PRIMARY KEY (`id`)
) ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `home_organizer`.`category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `home_organizer`.`category` ;

CREATE TABLE IF NOT EXISTS `home_organizer`.`category` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `group_id` INT NOT NULL,
  `name` VARCHAR(60) NOT NULL,
  `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` TIMESTAMP NULL DEFAULT NULL,
  `delete_time` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `fk_category_group1_idx` (`group_id`)
)ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_polish_ci;

ALTER TABLE `home_organizer`.`category`
ADD CONSTRAINT `fk_category_group1` FOREIGN KEY (`group_id`) REFERENCES `home_organizer`.`group` (`id`);

-- -----------------------------------------------------
-- Table `home_organizer`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `home_organizer`.`user` ;

CREATE TABLE IF NOT EXISTS `home_organizer`.`user` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(16) NOT NULL,
  `email` VARCHAR(255) NULL DEFAULT NULL,
  `password` VARCHAR(32) NOT NULL,
  `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` TIMESTAMP NULL DEFAULT NULL,
  `delete_time` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_polish_ci;


-- -----------------------------------------------------
-- Table `home_organizer`.`expenses`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `home_organizer`.`expenses` ;

CREATE TABLE IF NOT EXISTS `home_organizer`.`expenses` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `group_id` INT NOT NULL,
  `name` VARCHAR(60) NOT NULL,
  `value` DECIMAL(10,0) NOT NULL,
  `payer_id` INT(11) NOT NULL,
  `recipient_id` INT(11) NOT NULL,
  `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` TIMESTAMP NULL DEFAULT NULL,
  `delete_time` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `fk_expenses_user1_idx` (`payer_id`),
  KEY `fk_expenses_user2_idx` (`recipient_id`),
  KEY `fk_expenses_group1_idx` (`group_id`)
) ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_polish_ci;

ALTER TABLE `home_organizer`.`expenses`
ADD CONSTRAINT `fk_expenses_group1` FOREIGN KEY (`group_id`) REFERENCES `home_organizer`.`group` (`id`),
ADD CONSTRAINT `fk_expenses_user1` FOREIGN KEY (`payer_id`) REFERENCES `home_organizer`.`user` (`id`),
ADD CONSTRAINT `fk_expenses_user2` FOREIGN KEY (`recipient_id`) REFERENCES `home_organizer`.`user` (`id`);
-- -----------------------------------------------------
-- Table `home_organizer`.`expenses_settings`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `home_organizer`.`expenses_settings` ;

CREATE TABLE IF NOT EXISTS `home_organizer`.`expenses_settings` (
  `user1_id` INT(11) NOT NULL,
  `user2_id` INT(11) NOT NULL,
  `group_id` INT NOT NULL,
  `value` FLOAT NOT NULL,
  `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` TIMESTAMP NULL DEFAULT NULL,
  `delete_time` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`user1_id`, `user2_id`),
  KEY `fk_expenses_settings_user1_idx` (`user1_id`),
  KEY `fk_expenses_settings_user2_idx` (`user2_id`),
  KEY `fk_expenses_settings_group1_idx` (`group_id`)
) ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_polish_ci;

ALTER TABLE `home_organizer`.`expenses_settings`
ADD CONSTRAINT `fk_expenses_settings_group1` FOREIGN KEY (`group_id`) REFERENCES `home_organizer`.`group` (`id`),
ADD CONSTRAINT `fk_expenses_settings_user1` FOREIGN KEY (`user1_id`) REFERENCES `home_organizer`.`user` (`id`),
ADD CONSTRAINT `fk_expenses_settings_user2` FOREIGN KEY (`user2_id`) REFERENCES `home_organizer`.`user` (`id`);

-- -----------------------------------------------------
-- Table `home_organizer`.`shopping_list`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `home_organizer`.`shopping_list` ;

CREATE TABLE IF NOT EXISTS `home_organizer`.`shopping_list` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `group_id` INT NOT NULL,
  `name` VARCHAR(60) NOT NULL,
  `description` VARCHAR(200) NOT NULL,
  `visible` TINYINT(1) NOT NULL,
  `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` TIMESTAMP NULL DEFAULT NULL,
  `delete_time` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `fk_shopping_list_group1_idx` (`group_id`)
)ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_polish_ci;

ALTER TABLE `home_organizer`.`shopping_list`
ADD CONSTRAINT `fk_shopping_list_group1` FOREIGN KEY (`group_id`) REFERENCES `home_organizer`.`group` (`id`);
-- -----------------------------------------------------
-- Table `home_organizer`.`state`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `home_organizer`.`state` ;

CREATE TABLE IF NOT EXISTS `home_organizer`.`state` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(60) NULL DEFAULT NULL,
  `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` TIMESTAMP NULL DEFAULT NULL,
  `delete_time` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_polish_ci;


-- -----------------------------------------------------
-- Table `home_organizer`.`subcategory`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `home_organizer`.`subcategory` ;

CREATE TABLE IF NOT EXISTS `home_organizer`.`subcategory` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `group_id` INT NOT NULL,
  `name` VARCHAR(60) NOT NULL,
  `category_id` INT(11) NOT NULL,
  `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` TIMESTAMP NULL DEFAULT NULL,
  `delete_time` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `fk_subcategory_group1_idx` (`group_id`),
  KEY `fk_subcategory_category1_idx` (`category_id`)
) ENGINE = InnoDB
AUTO_INCREMENT = 22
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_polish_ci;

ALTER TABLE `home_organizer`.`subcategory`
ADD CONSTRAINT `fk_subcategory_group1` FOREIGN KEY (`group_id`) REFERENCES `home_organizer`.`group` (`id`),
ADD CONSTRAINT `fk_subcategory_category1` FOREIGN KEY (`category_id`) REFERENCES `home_organizer`.`category` (`id`);
-- -----------------------------------------------------
-- Table `home_organizer`.`item`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `home_organizer`.`item` ;

CREATE TABLE IF NOT EXISTS `home_organizer`.`item` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `group_id` INT NOT NULL,
  `name` VARCHAR(60) NOT NULL,
  `state_id` INT(11) NULL DEFAULT NULL,
  `quantity` VARCHAR(60) NULL DEFAULT NULL,
  `category_id` INT(11) NOT NULL,
  `bought` TIMESTAMP NULL DEFAULT NULL,
  `shopping_list_id` INT(11) NULL DEFAULT NULL,
  `counter` BIGINT NOT NULL DEFAULT 0,
  `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` TIMESTAMP NULL DEFAULT NULL,
  `delete_time` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `fk_item_group1_idx` (`group_id`),
  KEY `fk_item_subcategory1_idx` (`category_id`),
  KEY `fk_item_state1_idx` (`state_id`),
  KEY `fk_item_shopping_list1_idx` (`shopping_list_id`)
) ENGINE = InnoDB
AUTO_INCREMENT = 58
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_polish_ci;

ALTER TABLE `home_organizer`.`item`
ADD CONSTRAINT `fk_item_group1` FOREIGN KEY (`group_id`) REFERENCES `home_organizer`.`group` (`id`),
ADD CONSTRAINT `fk_item_subcategory1` FOREIGN KEY (`category_id`) REFERENCES `home_organizer`.`subcategory` (`id`),
ADD CONSTRAINT `fk_item_state1` FOREIGN KEY (`state_id`) REFERENCES `home_organizer`.`state` (`id`),
ADD CONSTRAINT `fk_item_shopping_list1` FOREIGN KEY (`shopping_list_id`) REFERENCES `home_organizer`.`shopping_list` (`id`);
-- -----------------------------------------------------
-- Table `home_organizer`.`user_groups`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `home_organizer`.`user_groups` ;

CREATE TABLE IF NOT EXISTS `home_organizer`.`user_groups` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT(11) NOT NULL,
  `group_id` INT NOT NULL,
  `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` TIMESTAMP NULL,
  `delete_time` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  KEY `fk_user_groups_group1_idx` (`group_id`),
  KEY `fk_user_groups_user1_idx` (`user_id`)
) ENGINE = InnoDB;

ALTER TABLE `home_organizer`.`user_groups`
ADD CONSTRAINT `fk_user_groups_group1` FOREIGN KEY (`group_id`) REFERENCES `home_organizer`.`group` (`id`),
ADD CONSTRAINT `fk_user_groups_user1` FOREIGN KEY (`user_id`) REFERENCES `home_organizer`.`user` (`id`);

USE `home_organizer` ;

-- -----------------------------------------------------
-- Placeholder table for view `home_organizer`.`permanent_item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `home_organizer`.`permanent_item` (`id` INT, `group_id` INT, `name` INT, `state_id` INT, `category_id` INT, `counter` BIGINT, `create_time` INT, `update_time` INT, `delete_time` INT);

-- -----------------------------------------------------
-- Placeholder table for view `home_organizer`.`saldo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `home_organizer`.`saldo` (`payer_id` INT, `group_id` INT, `recipient_id` INT, `value` INT);

-- -----------------------------------------------------
-- Placeholder table for view `home_organizer`.`shopping_item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `home_organizer`.`shopping_item` (`id` INT, `group_id` INT, `name` INT, `shopping_list_id` INT, `state_id` INT, `counter` BIGINT, `quantity` INT, `category_id` INT, `bought` INT, `create_time` INT, `update_time` INT, `delete_time` INT, `visible` INT, `archived` INT);

-- -----------------------------------------------------
-- Placeholder table for view `home_organizer`.`temporary_item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `home_organizer`.`temporary_item` (`id` INT, `group_id` INT, `name` INT, `shopping_list_id` INT, `quantity` INT, `category_id` INT, `bought` INT, `create_time` INT, `update_time` INT, `delete_time` INT);

-- -----------------------------------------------------
-- View `home_organizer`.`permanent_item`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `home_organizer`.`permanent_item`;
DROP VIEW IF EXISTS `home_organizer`.`permanent_item` ;
USE `home_organizer`;
CREATE  OR REPLACE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `permanent_item`  AS  select `item`.`id` AS `id`, `item`.`group_id` AS `group_id`, `item`.`name` AS `name`,`item`.`state_id` AS `state_id`,`item`.`category_id` AS `category_id`, `item`.`counter` AS `counter`, `item`.`create_time` AS `create_time`,`item`.`update_time` AS `update_time`,`item`.`delete_time` AS `delete_time` from `item` where isnull(`item`.`shopping_list_id`);

-- -----------------------------------------------------
-- View `home_organizer`.`saldo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `home_organizer`.`saldo`;
DROP VIEW IF EXISTS `home_organizer`.`saldo` ;
USE `home_organizer`;
CREATE  OR REPLACE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `saldo`  AS  select `expenses`.`payer_id` AS `payer_id`,`expenses`.`recipient_id` AS `recipient_id`, `expenses`.`group_id` AS `group_id`, `expenses`.`value` AS `value` from `expenses`;

-- -----------------------------------------------------
-- View `home_organizer`.`shopping_item`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `home_organizer`.`shopping_item`;
DROP VIEW IF EXISTS `home_organizer`.`shopping_item` ;
USE `home_organizer`;
CREATE  OR REPLACE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `shopping_item`  AS  select `item`.`id` AS `id`, `item`.`group_id` AS `group_id`, `item`.`name` AS `name`,`item`.`shopping_list_id` AS `shopping_list_id`,`item`.`state_id` AS `state_id`,`item`.`counter` AS `counter`, `item`.`quantity` AS `quantity`,`item`.`category_id` AS `category_id`,`item`.`bought` AS `bought`,`item`.`create_time` AS `create_time`,`item`.`update_time` AS `update_time`,`item`.`delete_time` AS `delete_time`,`sl`.`visible` AS `visible`,`sl`.`delete_time` AS `archived` from (`item` left join `shopping_list` `sl` on((`sl`.`id` = `item`.`shopping_list_id`)));

-- -----------------------------------------------------
-- View `home_organizer`.`temporary_item`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `home_organizer`.`temporary_item`;
DROP VIEW IF EXISTS `home_organizer`.`temporary_item` ;
USE `home_organizer`;
CREATE  OR REPLACE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `temporary_item`  AS  select `item`.`id` AS `id`, `item`.`group_id` AS `group_id`, `item`.`name` AS `name`,`item`.`shopping_list_id` AS `shopping_list_id`,`item`.`quantity` AS `quantity`,`item`.`category_id` AS `category_id`,`item`.`bought` AS `bought`,`item`.`create_time` AS `create_time`,`item`.`update_time` AS `update_time`,`item`.`delete_time` AS `delete_time` from `item` where (`item`.`shopping_list_id` is not null);

INSERT INTO `state` (`id`, `name`, `create_time`, `update_time`, `delete_time`) VALUES
(1, 'CRITICAL', CURRENT_TIMESTAMP, NULL, NULL),
(2, 'LITTLE', CURRENT_TIMESTAMP, NULL, NULL),
(3, 'MEDIUM', CURRENT_TIMESTAMP, NULL, NULL),
(4, 'LOT', CURRENT_TIMESTAMP, NULL, NULL);

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;